
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "left+-left*/rightUMINUSNUMBERinput : exprinput : errorexpr : expr '+' expr\n            | expr '-' expr\n            | expr '*' expr\n            | expr '/' exprexpr : '-' expr %prec UMINUSexpr : '(' expr ')'expr : NUMBER"
    
_lr_action_items = {'error':([0,],[3,]),'-':([0,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[4,8,4,4,-9,4,4,4,4,-7,8,-3,-4,-5,-6,-8,]),'(':([0,4,5,7,8,9,10,],[5,5,5,5,5,5,5,]),'NUMBER':([0,4,5,7,8,9,10,],[6,6,6,6,6,6,6,]),'$end':([1,2,3,6,11,13,14,15,16,17,],[0,-1,-2,-9,-7,-3,-4,-5,-6,-8,]),'+':([2,6,11,12,13,14,15,16,17,],[7,-9,-7,7,-3,-4,-5,-6,-8,]),'*':([2,6,11,12,13,14,15,16,17,],[9,-9,-7,9,9,9,-5,-6,-8,]),'/':([2,6,11,12,13,14,15,16,17,],[10,-9,-7,10,10,10,-5,-6,-8,]),')':([6,11,12,13,14,15,16,17,],[-9,-7,17,-3,-4,-5,-6,-8,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'input':([0,],[1,]),'expr':([0,4,5,7,8,9,10,],[2,11,12,13,14,15,16,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> input","S'",1,None,None,None),
  ('input -> expr','input',1,'p_input_valid','validador - copia.py',28),
  ('input -> error','input',1,'p_input_error','validador - copia.py',32),
  ('expr -> expr + expr','expr',3,'p_expr_binop','validador - copia.py',36),
  ('expr -> expr - expr','expr',3,'p_expr_binop','validador - copia.py',37),
  ('expr -> expr * expr','expr',3,'p_expr_binop','validador - copia.py',38),
  ('expr -> expr / expr','expr',3,'p_expr_binop','validador - copia.py',39),
  ('expr -> - expr','expr',2,'p_expr_uminus','validador - copia.py',43),
  ('expr -> ( expr )','expr',3,'p_expr_group','validador - copia.py',47),
  ('expr -> NUMBER','expr',1,'p_expr_number','validador - copia.py',51),
]
